title: "EmWaveTech"
email: marketing@koottali.com
timezone: UTC
url: https://emwavetech.com
baseurl: "/"
permalink: "/:title/"
logo: "assets/images/main.svg"
favicon: "assets/images/ktnew.svg"
author: emwavetech
paginate: 30
disqus: "emwavetech.com"
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-Z9LKZ0B57Y

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: "assets/images/sal.png"
    email: marketing@koottali.com
    web: https://www.pockio.app
    twitter: https://twitter.com/koottali
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: Pockio - Smart Money Habits
    display_name: Pockio - Smart Money Habits
    avatar: "assets/images/john.png"
    email: marketing@koottali.com
    web: https://www.pockio.app/
    twitter: https://twitter.com/koottali
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/pockio_app/
  facebook: https://www.facebook.com/pockioapp
  twitter: https://twitter.com/pockio

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
